import AppKit
import Foundation

/// Polls the shared pasteboard and forwards safe plain-text captures.
@MainActor
final class ClipboardWatcher {
    private let settings: SettingsStore
    private let pasteboard: NSPasteboard
    private let onCapture: (String) -> Void

    private var timer: Timer?
    private var lastSeenChangeCount: Int
    private var ignoredChangeCounts = Set<Int>()
    private var lastCapturedText: String?

    private static let pollInterval: TimeInterval = 0.75
    private static let ignoredPasteboardTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.apple.is-sensitive"
    ]

    init(
        settings: SettingsStore,
        pasteboard: NSPasteboard = .general,
        onCapture: @escaping (String) -> Void
    ) {
        self.settings = settings
        self.pasteboard = pasteboard
        self.onCapture = onCapture
        self.lastSeenChangeCount = pasteboard.changeCount
    }

    func start() {
        guard timer == nil else {
            return
        }

        lastSeenChangeCount = pasteboard.changeCount

        let timer = Timer(timeInterval: Self.pollInterval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.pollPasteboard()
            }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        let timer = self.timer
        self.timer = nil

        timer?.invalidate()
    }

    @discardableResult
    func writeToPasteboard(_ text: String) -> Bool {
        pasteboard.clearContents()
        let success = pasteboard.setString(text, forType: .string)
        guard success else {
            return false
        }

        ignoredChangeCounts.insert(pasteboard.changeCount)
        return true
    }

    private func pollPasteboard() {
        let currentChangeCount = pasteboard.changeCount

        if consumeIgnoredChangeCount(currentChangeCount) {
            updateLastSeenChangeCount(currentChangeCount)
            return
        }

        let previousChangeCount = readLastSeenChangeCount()
        guard currentChangeCount != previousChangeCount else {
            return
        }

        updateLastSeenChangeCount(currentChangeCount)

        guard settings.isCapturePaused == false else {
            return
        }

        guard let items = pasteboard.pasteboardItems, items.isEmpty == false else {
            return
        }

        guard items.contains(where: shouldSkipPasteboardItem) == false else {
            return
        }

        guard let text = firstPlainText(in: items)?.trimmingCharacters(in: .whitespacesAndNewlines),
              text.isEmpty == false else {
            return
        }

        guard text.utf8.count <= settings.maxItemSizeBytes else {
            return
        }

        let filter = SecretFilter(skipShortOneTimeCodes: settings.skipShortOneTimeCodes)
        guard filter.shouldReject(text) == false else {
            return
        }

        guard text != readLastCapturedText() else {
            return
        }

        rememberCapturedText(text)
        onCapture(text)
    }

    private func shouldSkipPasteboardItem(_ item: NSPasteboardItem) -> Bool {
        let types = item.types.map(\.rawValue)
        return Self.ignoredPasteboardTypes.isDisjoint(with: types) == false
    }

    private func firstPlainText(in items: [NSPasteboardItem]) -> String? {
        for item in items {
            if let text = item.string(forType: .string) {
                return text
            }
        }

        return nil
    }

    private func consumeIgnoredChangeCount(_ changeCount: Int) -> Bool {
        guard ignoredChangeCounts.contains(changeCount) else {
            return false
        }

        ignoredChangeCounts.remove(changeCount)
        return true
    }

    private func updateLastSeenChangeCount(_ changeCount: Int) {
        lastSeenChangeCount = changeCount
    }

    private func readLastSeenChangeCount() -> Int {
        return lastSeenChangeCount
    }

    private func readLastCapturedText() -> String? {
        return lastCapturedText
    }

    private func rememberCapturedText(_ text: String) {
        lastCapturedText = text
    }
}
